(define (domain pr2-tamp)
  (:requirements :strips :equality)
  ;(:constants @sink @stove)
  (:predicates
    (Arm ?a)
    (Stackable ?o ?r)
    (disc ?disc)
    (peg ?peg)
    (Sink ?r)
    (Stove ?r)
    (Type ?t ?b)
    (AConf ?q)
    (Pose ?o ?p)
    (Grasp ?o ?g)
    (Kin ?a ?o ?p ?g ?r ?rp ?q ?t)
    ; (BaseMotion ?q1 ?t ?q2)
    (ArmMotion ?a ?q1 ?t ?q2)
    ;(ApproachMotion ?a ?q ?t ?o ?p ?g)
    (Supported ?o ?p ?r ?rp) ; ?rp
    (BTraj ?t)
    (ATraj ?t)

    (CFreePosePose ?o ?p ?o2 ?p2)
    (CFreeApproachPose ?o ?p ?g ?o2 ?p2)
    (CFreeTrajPose ?t ?o2 ?p2)
    (CFreeTrajGraspPose ?t ?a ?o1 ?g1 ?o2 ?p2)
    (KinCheck ?o ?p ?r ?rp ?g ?q)

    (AtPose ?o ?p)
    (AtGrasp ?a ?o ?g)
    (HandEmpty ?a)
    (AtBConf ?q)
    (AtAConf ?a ?q)
    (CanMove)
    (Cleaned ?o)
    (Cooked ?o)
    (Smaller ?o1 ?o2)

    (On ?o ?r)
    (Holding ?a ?o)
    (UnsafePose ?o ?p)
    (UnsafeApproach ?o ?p ?g)
    (UnsafeATraj ?t)
    (FeasibleKin ?o ?p ?r ?rp ?g ?q)
    ;(UnsafeBTraj ?t)
  )
  (:functions
    (Distance ?q1 ?q2)
  )

  ; (:action move_base
  ;   :parameters (?q1 ?q2 ?t)
  ;   :precondition (and (BaseMotion ?q1 ?t ?q2)
  ;                      (AtBConf ?q1) (CanMove)
  ;                      ;(not (UnsafeBTraj ?t))
  ;                  )
  ;   :effect (and (AtBConf ?q2)
  ;                (not (AtBConf ?q1)) (not (CanMove))
  ;                ; (increase (total-cost) (Distance ?q1 ?q2)))
  ;                ; (increase (total-cost) (MoveCost ?t)))
  ; )
  (:action move_arm
   :parameters (?a ?q1 ?q2 ?t)
   :precondition (and (ArmMotion ?a ?q1 ?t ?q2)
                      (AtAConf ?a ?q1)
                      (CanMove)
                      (not (UnsafeATraj ?t)) 
                      )
   :effect (and (AtAConf ?a ?q2)
                (not (AtAConf ?a ?q1))
                (not (CanMove))
                ;(increase (total-cost) (Distance ?q1 ?q2))
                )
  )

  (:action pick
    :parameters (?a ?o ?r ?rp ?p ?g ?q ?t) ; ?rp 
    :precondition (and (Kin ?a ?o ?p ?g ?r ?rp ?q ?t)
                       (AtPose ?o ?p) (HandEmpty ?a) (AtAConf ?a ?q)
                       (not (UnsafeApproach ?o ?p ?g))
                       (not (UnsafeATraj ?t))
                       (Supported ?o ?p ?r ?rp) ; ?rp
                       (Cleaned ?o)
                       (FeasibleKin ?o ?p ?r ?rp ?g ?q)
                       ;(Pose ?o ?p)
                       ;(Pose ?r ?rp)
                  )
    :effect (and (AtGrasp ?a ?o ?g)
                 (not (AtPose ?o ?p)) (not (HandEmpty ?a))
                 (CanMove)
                 (Cleaned ?r)
                 )
  )
  (:action place
    :parameters (?a ?o ?r ?rp ?p ?g ?q ?t) ; ?rp 
    :precondition (and (Kin ?a ?o ?p ?g ?r ?rp ?q ?t)
                       (AtGrasp ?a ?o ?g) (AtAConf ?a ?q)
                       (not (UnsafePose ?o ?p))
                       (not (UnsafeApproach ?o ?p ?g))
                       (FeasibleKin ?o ?p ?r ?rp ?g ?q)
                       (not (UnsafeATraj ?t))
                       (Smaller ?o ?r)
                       (Supported ?o ?p ?r ?rp) ; ?rp
                       ;(Pose ?o ?p)
                       ;(Pose ?r ?rp)
                       (Cleaned ?r)
                  )
    :effect (and (AtPose ?o ?p) (HandEmpty ?a)
                 (not (AtGrasp ?a ?o ?g))
                 (CanMove)
                 (not (Cleaned ?r))
                 
                 )
  )

  (:action clean
    :parameters (?o ?r)
    :precondition (and (Stackable ?o ?r) (Sink ?r) ; (Sink ?r)
                       (On ?o ?r))
    :effect (Cleaned ?o)
  )
  (:action cook
    :parameters (?o ?r)
    :precondition (and (Stackable ?o ?r) (Stove ?r) ; (Stove ?r)
                       (On ?o ?r) (Cleaned ?o))
    :effect (and (Cooked ?o)
                 (not (Cleaned ?o)))
  )

  (:derived (On ?o ?r)
    (exists (?p ?rp) (and (Supported ?o ?p ?r ?rp) ; ?rp
                      (AtPose ?o ?p)))
  )
  (:derived (Holding ?a ?o)
    (exists (?g) (and (Arm ?a) (Grasp ?o ?g)
                      (AtGrasp ?a ?o ?g)))
  )

  (:derived (FeasibleKin ?o ?p ?r ?rp ?g ?q)
    (exists (?a ?t) (and (Kin ?a ?o ?p ?g ?r ?rp ?q ?t)
                      (KinCheck ?o ?p ?r ?rp ?g ?q)))
  )

  (:derived (UnsafePose ?o ?p)
    (exists (?o2 ?p2) (and (Pose ?o ?p) (Pose ?o2 ?p2) (not (= ?o ?o2))
                           (not (CFreePosePose ?o ?p ?o2 ?p2))
                           (AtPose ?o2 ?p2)))
  )
  (:derived (UnsafeApproach ?o ?p ?g)
    (exists (?o2 ?p2) (and (Pose ?o ?p) (Grasp ?o ?g) (Pose ?o2 ?p2) (not (= ?o ?o2))
                           (not (CFreeApproachPose ?o ?p ?g ?o2 ?p2))
                           (AtPose ?o2 ?p2)))
  )
  (:derived (UnsafeATraj ?t)
    (exists (?o2 ?p2) (and (ATraj ?t) (Pose ?o2 ?p2)
                           (not (CFreeTrajPose ?t ?o2 ?p2))
                           (AtPose ?o2 ?p2)))
  )
  ;(:derived (UnsafeBTraj ?t) (or
  ;  ;(exists (?o2 ?p2) (and (BTraj ?t) (Pose ?o2 ?p2)
  ;  ;                       (not (CFreeTrajPose ?t ?o2 ?p2))
  ;  ;                       (AtPose ?o2 ?p2)))
  ;  (exists (?a ?o1 ?g1 ?o2 ?p2) (and (BTraj ?t) (Arm ?a) (Grasp ?o1 ?g1) (Pose ?o2 ?p2)
  ;                                    (not (CFreeTrajGraspPose ?t ?a ?o1 ?g1 ?o2 ?p2)) (not (= ?o1 ?o2))
  ;                                    (AtGrasp ?a ?o1 ?g1) (AtPose ?o2 ?p2)))
  ;))

)